export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const IS_LOADING = "IS_LOADING";
export const SET_BOOK_DATE = "SET_BOOK_DATE";

export const GET_ALL_COUNSELLOR = "GET_ALL_COUNSELLOR";
export const GET_COUNSELLOR = "GET_COUNSELLOR";
export const SET_SCHEDULE = "SET_SCHEDULE";

export const SET_BOOKING = "SET_BOOKING";
